#UseDockerizedinfrastructure
sudo:false

#Usenode_jsenvironnement
language:node_js
node_js:
-"7"

#CacheGcloudSDKbetweencommands
cache:
directories:
-"$HOME/google-cloud-sdk/"

#Installservices
services:
-docker

#Installaddons
addons:
apt:
packages:
-default-jre

#Setenvvars
env:
global:
-GOOGLE_APPLICATION_CREDENTIALS=~/gcloud-service-key.json
-PROJECT_NAME=travis-ci-280602
-PROJECT_IMAGES=jokedose-travisci
-CLUSTER_NAME=cluster-jokedose-travisci
-CLOUDSDK_COMPUTE_ZONE=asia-southeast1-a
-CLOUDSDK_CORE_DISABLE_PROMPTS=1
-NODE_ENV=CI

before_install:
-if[!-d"$HOME/google-cloud-sdk/bin"];thenrm-rf"$HOME/google-cloud-sdk";curlhttps://sdk.cloud.google.com|bash>/dev/null;fi
-source$HOME/google-cloud-sdk/path.bash.inc
-ls-l${HOME}/google-cloud-sdk/
-gcloud--quietversion
-gcloud--quietcomponentsupdate
-gcloud--quietcomponentsupdatebeta

install:
-npminstall

script:
-echo"skiptests"

before_deploy:
-gcloud--quietcomponentsupdatekubectl
-echo${GCLOUD_SERVICE_KEY_TEST}
-echo${GCLOUD_SERVICE_KEY_TEST}|base64--decode-i
-echo${GCLOUD_SERVICE_KEY_TEST}|base64--decode-i>$HOME/google-cloud-sdk/gcloud-service-key.json

deploy:
-provider:script
script:./resources/deploy.sh
skip_cleanup:true
on:
branch:master

#notifications:
#slack:<key>