# Use Dockerized infrastructure
sudo: false

# Use node_js environnement
language: node_js
node_js:
  - "7"

# Cache Gcloud SDK between commands
cache:
  directories:
    - "$HOME/google-cloud-sdk/"

# Install services
services:
  - docker

# Install addons
addons:
  apt:
    packages:
    - default-jre

# Set env vars
env:
  global:
    - GOOGLE_APPLICATION_CREDENTIALS=~/gcloud-service-key.json
    - PROJECT_NAME=travis-ci-280602
    - PROJECT_IMAGES=jokedose-travisci
    - CLUSTER_NAME=cluster-jokedose-travisci
    - CLOUDSDK_COMPUTE_ZONE=asia-southeast1-a
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1 
    - NODE_ENV=CI

before_install:
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf "$HOME/google-cloud-sdk"; curl https://sdk.cloud.google.com | bash > /dev/null; fi
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud iam service-accounts keys create --iam-account 483190874546-compute@developer.gserviceaccount.com gcloud-service-key.json
  - gcloud --quiet version
  - gcloud --quiet components update
  - gcloud --quiet components update beta

install:
  - npm install

script:
  - echo "skip tests"

before_deploy:
  - gcloud --quiet components update kubectl

deploy:
  - provider: script
    script: ./resources/deploy.sh
    skip_cleanup: true
    on:
      branch: master

#notifications:
#  slack: <key>